import { completeQuote, createProcurementState, transition } from "./state/procurementDemo.js";
import "./styles.css";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
const app = document.querySelector("#app");
let state = createProcurementState();
let screen = "overview";

const phases = ["Request", "Priorities", "Brief", "Discover", "Quotes", "Negotiate", "Decision", "Recommend", "Plan"];
const label = (value) => value.replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
const tag = (text, tone = "") => `<span class="tag ${tone}"><i></i>${text}</span>`;
const phaseIndex = () => ({ draft: 0, briefing: 2, sourcing: 3, quoting: 4, negotiating: 5, needs_decision: 6, recommending: 7, plan_ready: 8, complete: 8, blocked: 6 })[state.phase];

function shell(content) {
  app.innerHTML = `<div class="app-shell"><aside class="sidebar"><div class="brand"><span class="mark">▲</span>TAKEOFF</div><div class="workspace"><span class="avatar">AC</span><span><b>Alder Carter</b><small>Custom Home · Contractor</small></span></div><nav>${[["overview", "Overview", "⌂"], ["requirements", "Requirements", "▤"], ["priorities", "Brief & priorities", "◇"], ["suppliers", "Suppliers", "◌"], ["quotes", "Quotes", "↔"], ["negotiation", "Negotiation", "⇄"], ["evidence", "Activity & evidence", "◫"]].map(([key, text, icon]) => `<button class="nav-item ${screen === key ? "active" : ""}" data-screen="${key}"><span>${icon}</span>${text}</button>`).join("")}</nav><div class="sidebar-bottom"><div class="mode-label"><span class="pulse"></span>${state.mode.toUpperCase()} REPLAY</div><small>Public supplier data only</small></div></aside><main><header><div><p class="eyebrow">${state.project.name.toUpperCase()} · ${state.project.location.toUpperCase()}</p><h1>House materials procurement</h1></div><div class="header-actions">${tag(state.mode === "demo" ? "Demo replay" : "Live", "mode")}<button class="quiet" data-screen="evidence">Evidence</button><span class="profile">AC</span></div></header><section class="stagebar"><div class="stage-track">${phases.map((phase, index) => `<button data-stage="${index}" class="stage ${index < phaseIndex() ? "done" : ""} ${index === phaseIndex() ? "current" : ""}"><span>${index < phaseIndex() ? "✓" : index + 1}</span>${phase}</button>`).join("")}</div><div class="agent-state"><span class="agent-dot"></span><b>Takeoff / Hermes</b><small>${label(state.phase)}</small></div></section>${content}</main></div>`;
  bind();
}

function overview() {
  const complete = completeQuote(state);
  shell(`<section class="hero-grid"><article class="card task-card"><p class="eyebrow">PROCUREMENT REQUEST</p><h2>Build a reliable material package for the Custom Home.</h2><p class="lead">Takeoff will confirm requirements, learn what matters, then source and negotiate with suppliers. It will never place an external order.</p><div class="request-meta"><span><small>Needed by</small><b>${state.project.neededBy}</b></span><span><small>Request source</small><b>${state.project.source}</b></span><span><small>Requirements</small><b>${state.requirements.length} material lines</b></span></div><div class="decision-footer"><span>Start with imperfect information—Takeoff will flag what needs clarification.</span><button class="primary" data-event="start">Start procurement</button></div></article><aside class="card agent-card"><p class="eyebrow">TAKEOFF IS READY</p><h3>What happens next</h3><div class="checklist"><p><b>1</b> Understand your requirements</p><p><b>2</b> Ask what to optimize for</p><p><b>3</b> Source, compare, and negotiate</p><p><b>4</b> Bring back consequential choices</p></div></aside></section>${complete ? `<section class="card compact"><b>Supplier-market adapter loaded</b><span>${complete.name} has complete catalog coverage for this scenario; other suppliers remain partial until they issue a complete package.</span></section>` : ""}`);
}

function priorities() {
  shell(`<section class="focus-layout"><article class="card focus-card"><div class="card-kicker"><span class="agent-badge">✦</span> TAKEOFF / HERMES</div><h2>Before I contact suppliers, what matters most for this purchase?</h2><p class="lead">Your answer determines how I compare offers. Required specifications and the requested date remain constraints.</p><div class="priority-choice">${[["delivery", "Delivery certainty", "Materials arrive when the crew needs them"], ["quality", "Quality", "Exact specification and proven fit"], ["cost", "Cost", "Lowest complete payable package"], ["reliability", "Supplier reliability", "Known, responsive fulfillment"]].map(([key, title, description]) => `<button data-priority="${key}" class="priority-button ${state.priorities[key] === Math.max(...Object.values(state.priorities)) ? "selected" : ""}"><span class="radio"></span><span><b>${title}</b><small>${description}</small></span><strong>${state.priorities[key]}%</strong></button>`).join("")}</div><div class="natural-answer"><label>Tell Takeoff anything else that matters <textarea placeholder="For example: framing begins Friday; avoid substitutions."></textarea></label></div><div class="decision-footer"><span>Priority interview occurs before supplier discovery.</span><button class="primary" data-event="priorities-confirmed">Confirm priorities</button></div></article><aside class="card brief-side"><p class="eyebrow">HARD REQUIREMENTS</p>${state.requirements.slice(0, 4).map((item) => `<p><b>✓ ${item.name}</b><small>${item.quantity} ${item.unit} · ${item.specification}</small></p>`).join("")}<p class="muted">+ ${state.requirements.length - 4} additional requirements</p></aside></section>`);
}

function brief() {
  shell(`<section class="hero-grid"><article class="card"><div class="card-top"><div><p class="eyebrow">PROCUREMENT BRIEF</p><h2>Here's the strategy I'll use.</h2></div><button class="text-button" data-screen="priorities">Edit priorities</button></div><div class="brief-columns"><div><h3>Requirements</h3>${state.requirements.map((item) => `<p class="line"><b>✓ ${item.name}</b><small>${item.quantity} ${item.unit} · ${item.specification}</small></p>`).join("")}</div><div><h3>Priorities</h3>${Object.entries(state.priorities).map(([key, value]) => `<div class="bar"><span>${key === "delivery" ? "Delivery certainty" : label(key)}</span><em>${value}%</em><i><b style="width:${value * 2}%"></b></i></div>`).join("")}<h3 class="constraint-title">Constraints</h3><p class="line"><b>✓ Exact specification</b><small>Substitutions require explicit approval</small></p><p class="line"><b>✓ Requested delivery date</b><small>${state.project.neededBy}</small></p></div></div><div class="strategy-note">✦ <b>Strategy:</b> prioritize reliable, complete coverage before marginal line-item savings. Surface any delivery or substitution tradeoff for approval.</div><div class="decision-footer"><span>Changing priorities later will recalculate the strategy.</span><button class="primary" data-event="priorities-confirmed">Start sourcing</button></div></article><aside class="card agent-card"><p class="eyebrow">AGENT AUTHORITY</p><h3>Takeoff can</h3><div class="checklist"><p><b>✓</b> Research catalog availability</p><p><b>✓</b> Request comparable quotes</p><p><b>✓</b> Ask about package terms</p><p><b>!</b> Ask before changing a material, deadline, or budget</p></div></aside></section>`);
}

function suppliers() {
  shell(`<section class="card"><div class="card-top"><div><p class="eyebrow">SUPPLIER DISCOVERY</p><h2>Takeoff is working through the market.</h2></div>${tag("4 channels searched", "good")}</div><div class="working-steps"><div class="complete">✓ Requirements understood</div><div class="complete">✓ Procurement strategy confirmed</div><div class="active">◌ Searching supplier catalogs and channels</div><div>○ Requesting complete package terms</div><div>○ Clarifying availability and delivery</div></div><div class="supplier-grid">${state.quotes.map((quote) => `<article class="supplier-card"><div><span class="channel">${quote.channel}</span>${tag(quote.status, quote.complete ? "good" : "warn")}</div><h3>${quote.name}</h3><p>${quote.coverage} of ${state.requirements.length} requirements covered</p><div class="coverage"><i><b style="width:${quote.coverage / state.requirements.length * 100}%"></b></i></div><small>${quote.deliveryDays}-day delivery option · ${money.format(quote.freight)} delivery fee</small></article>`).join("")}</div><div class="decision-footer"><span>Partial supplier data is retained but cannot silently win.</span><button class="primary" data-event="quotes-ready">Review quotes</button></div></section>`);
}

function quotes() {
  shell(`<section class="card"><div class="card-top"><div><p class="eyebrow">NORMALIZED QUOTES</p><h2>Comparable terms, not just low prices.</h2><p class="lead">These are public catalog/package estimates from the supplier-market demo. Unknown or incomplete coverage stays visible.</p></div><button class="text-button" data-screen="evidence">Inspect sources</button></div><div class="quote-table"><div class="quote-head"><span>Supplier & source</span><span>Coverage</span><span>Delivery</span><span>Estimate</span><span>Status</span></div>${state.quotes.map((quote) => `<button class="quote-row" data-quote="${quote.id}"><span><b>${quote.name}</b><small>${quote.channel} · ${quote.lines.length} normalized lines</small></span><span><b>${quote.coverage}/${state.requirements.length}</b><small>${quote.complete ? "Complete package" : quote.unknowns[0]}</small></span><span><b>${quote.deliveryDays} days</b><small>${money.format(quote.freight)} fee</small></span><span><b>${money.format(quote.total)}</b><small>${quote.complete ? "Catalog estimate + delivery" : "Partial estimate only"}</small></span><span>${tag(quote.complete ? "Complete" : "Incomplete", quote.complete ? "good" : "warn")}<b class="chevron">›</b></span></button>`).join("")}</div><div class="decision-footer"><span>Takeoff will negotiate only against actual confirmed terms.</span><button class="primary" data-event="quotes-ready">Continue to negotiation</button></div></section>`);
}

function negotiation() {
  const complete = completeQuote(state);
  shell(`<section class="hero-grid"><article class="card"><div class="card-top"><div><p class="eyebrow">NEGOTIATION</p><h2>${complete.name}</h2><p class="lead">Takeoff requests only supported improvements and preserves the resulting offer history.</p></div>${tag("Awaiting supplier response", "warn")}</div><div class="timeline"><div><span>1</span><p><b>Supplier catalog estimate</b><small>${money.format(complete.total)} · ${complete.deliveryDays}-day delivery · ${money.format(complete.freight)} delivery fee</small></p></div><div><span>2</span><p><b>Takeoff action</b><small>Requested confirmed availability, package terms, and whether delivery can be improved.</small></p></div><div><span>3</span><p><b>Supplier response</b><small>Waiting. A proposal is not a confirmed saving.</small></p></div></div><div class="decision-footer"><span>Offers, counters, and superseded terms remain evidence.</span><button class="primary" data-event="decision-needed">Review delivery tradeoff</button></div></article><aside class="card"><p class="eyebrow">OTHER SUPPLIER SIGNALS</p>${state.quotes.filter((quote) => quote.id !== complete.id).map((quote) => `<p class="line"><b>${quote.name}</b><small>${quote.status} · ${quote.coverage}/${state.requirements.length} lines · ${quote.deliveryDays} days</small></p>`).join("")}</aside></section>`);
}

function decision() {
  shell(`<section class="focus-layout"><article class="card focus-card decision-card"><div class="card-kicker"><span class="agent-badge">✦</span> TAKEOFF NEEDS A DECISION ${tag("Action required", "urgent")}</div><h2>Would you trade the requested date for a lower complete package cost?</h2><p class="lead">The supplier market has a lower-cost partial supplier with a five-day delivery option, but it does not cover every required material. Keep the original delivery requirement, or authorize Takeoff to explore a later delivery only for eligible material lines?</p><div class="option-list"><button class="decision-option" data-event="choose-faster"><span class="radio"></span><span><b>Keep the requested delivery requirement</b><small>Favor complete, on-time coverage and do not relax the date.</small></span><strong>Protect schedule</strong><span class="arrow">→</span></button><button class="decision-option" data-event="choose-lower-cost"><span class="radio"></span><span><b>Explore lower-cost later delivery</b><small>Takeoff will seek a line-specific approval and keep all uncovered items explicit.</small></span><strong>May reduce cost</strong><span class="arrow">→</span></button></div><div class="decision-footer"><span>Your answer is recorded against this procurement task; it is not an order.</span></div></article><aside class="card brief-side"><p class="eyebrow">CURRENT BRIEF</p><h3>Delivery certainty is leading</h3><p class="lead">${state.priorities.delivery}% priority · ${state.project.neededBy}</p><p class="line"><b>Evidence</b><small>General has complete catalog coverage; lower-price suppliers are currently partial.</small></p></aside></section>`);
}

function recommendation() {
  const quote = completeQuote(state);
  shell(`<section class="hero-grid"><article class="card recommendation-card"><p class="eyebrow">TAKEOFF UPDATED THE PLAN</p><h2>Recommend ${quote.name}</h2><div class="recommendation-total"><span>Estimated complete package</span><strong>${money.format(quote.total)}</strong><small>Catalog estimate including ${money.format(quote.freight)} delivery fee · ${quote.deliveryDays}-day delivery option</small></div><h3>Why this is the current recommendation</h3><div class="reasons"><p><span>✓</span> Covers all ${state.requirements.length} requested materials.</p><p><span>✓</span> Each included product is an exact specification match.</p><p><span>✓</span> Keeps the contractor's requested delivery requirement intact.</p><p><span>✓</span> Other suppliers remain partial, so they cannot be presented as a complete cheaper alternative.</p></div><div class="strategy-note">✦ <b>Strategy updated:</b> prioritize complete, schedule-safe coverage. Continue negotiation only after an actual supplier counter is received.</div><div class="decision-footer"><span>Recommendation is based on the currently visible supplier-market state.</span><button class="primary" data-event="plan-ready">Review draft purchase plan</button></div></article><aside class="card"><p class="eyebrow">ALTERNATIVES</p>${state.quotes.filter((item) => item.id !== quote.id).map((item) => `<p class="line"><b>${item.name}</b><small>Not selected: ${item.unknowns[0] || "does not meet the selected strategy"}</small></p>`).join("")}</aside></section>`);
}

function plan() {
  const quote = completeQuote(state);
  shell(`<section class="card plan-card"><div class="card-top"><div><p class="eyebrow">DRAFT PURCHASE PLAN</p><h2>${quote.name}</h2><p class="lead">Draft only — no external order has been placed.</p></div>${tag("Draft", "mode")}</div><div class="plan-lines">${quote.lines.map((line) => `<div><span><b>${line.name}</b><small>${line.specification} · Exact match</small></span><span>${line.quantity} ${line.unit}</span><span>${money.format(line.unitPrice)} / ${line.unit}</span><b>${money.format(line.total)}</b></div>`).join("")}</div><div class="plan-total"><span>Materials subtotal</span><b>${money.format(quote.subtotal)}</b><span>Delivery fee</span><b>${money.format(quote.freight)}</b><strong>Total payable</strong><strong>${money.format(quote.total)}</strong></div><div class="conditions"><b>Conditions preserved</b><span>Availability and final price must be confirmed by the supplier before an order is authorized.</span></div></section>`);
}

function evidence() {
  shell(`<section class="hero-grid"><article class="card"><p class="eyebrow">ACTIVITY & EVIDENCE</p><h2>What Takeoff did, and what it learned.</h2><div class="event-list">${state.activity.map(([text, type], index) => `<div class="event"><span class="event-dot ${type}"></span><div><b>${text}</b><small>${type === "fact" ? "Observed supplier or task fact" : "Takeoff action"} · Event ${index + 1}</small></div></div>`).join("")}</div></article><aside class="card"><p class="eyebrow">SOURCE BOUNDARY</p><h3>Inspectable public information</h3><p class="lead">Catalog product, quantity, unit, stock, public prices, delivery options, issued offers, and contractor approvals are visible here.</p><div class="private-notice">🔒 Supplier cost basis, margins, negotiation floor, inventory strategy, and internal objectives remain private.</div><button class="primary wide" data-screen="quotes">Return to quote comparison</button></aside></section>`);
}

function render() {
  if (screen === "requirements") return shell(`<section class="card"><p class="eyebrow">REQUIREMENTS</p><h2>What Takeoff will procure</h2><p class="lead">Structured from the contractor request. Each material stays inspectable and must be covered by an eligible product.</p><div class="requirements-grid">${state.requirements.map((item) => `<article><span class="tag good"><i></i>Exact spec required</span><h3>${item.name}</h3><b>${item.quantity} ${item.unit}</b><p>${item.specification}</p></article>`).join("")}</div></section>`);
  if (screen === "priorities") return priorities(); if (screen === "suppliers") return suppliers(); if (screen === "quotes") return quotes(); if (screen === "negotiation") return negotiation(); if (screen === "evidence") return evidence();
  if (state.phase === "draft") return overview(); if (state.phase === "briefing") return priorities(); if (state.phase === "sourcing") return suppliers(); if (state.phase === "negotiating") return negotiation(); if (state.phase === "needs_decision" || state.phase === "blocked") return decision(); if (state.phase === "recommending") return recommendation(); if (state.phase === "plan_ready") return plan(); return brief();
}

function bind() {
  document.querySelectorAll("[data-screen]").forEach((button) => button.addEventListener("click", () => { screen = button.dataset.screen; render(); }));
  document.querySelectorAll("[data-event]").forEach((button) => button.addEventListener("click", () => { state = transition(state, button.dataset.event); screen = "overview"; render(); }));
  document.querySelectorAll("[data-priority]").forEach((button) => button.addEventListener("click", () => { const focus = button.dataset.priority; const rest = Object.keys(state.priorities).filter((key) => key !== focus); state = { ...state, priorities: { ...state.priorities, [focus]: 45, ...Object.fromEntries(rest.map((key) => [key, key === "delivery" ? 25 : 15])) } }; render(); }));
  document.querySelectorAll("[data-stage]").forEach((button) => button.addEventListener("click", () => { const target = Number(button.dataset.stage); screen = ["overview", "priorities", "priorities", "suppliers", "quotes", "negotiation", "overview", "overview", "overview"][target]; render(); }));
}
render();
